### ISSUE TITLE
Inconsistent penetration_depth

### ISSUE THREAD

**Issue by vulevukusej** [humanoid-path-planner/hpp-fcl#357] opened 2022-11-15 16:15 UTC
Howdy - I'm cross-posting from https://github.com/IfcOpenShell/IfcOpenShell/issues/2430.  Is there any way I can refine the results such that the penetration depth calculated is correct?

**Comment by jcarpent** [comment] 2022-11-15 17:29
Thanks @vulevukusej for your interest in hpp-fcl.
To move forward on this topic, it would be nice to have some context and maybe a reproducing example in Python to validate the issue. Could you provide them?

**Comment by jmirabel** [comment] 2022-11-15 22:39
If you are talking about penetration depth for meshes, then it is expected that the value isn't meaningful globally. The penetration depth has a meaning only locally, for the two triangles in contact. The real penetration depth for 2D surfaces (aka a mesh) is in general hard to compute and is likely out of the scope of this library.

If you want meaningful penetration depth, use convex objects instead. E.g. decompose your object into convex ones (shouldn't be hard for what I saw on the other issue).

**Comment by vulevukusej** [comment] 2022-11-16 08:36
@jmirabel thanks for the explanation.

**Comment by jmirabel** [comment] 2022-11-16 08:54
Closing since it seems it answer your question. I let you re-open if I'm wrong.

**Closed by jmirabel** 2022-11-16 08:54 UTC
